#!/bin/bash
# script par ainstalar svxlink 15.11
while true
do
clear

echo "\33[1;32m   ********************************************************************"
echo "   *  MENU PARA INSTALAR SVXLINK 15.11 y QTEL EN LINUX o RASPBERRY PI *"
echo "   *                           \33[1;31mby EA3EIZ\33[1;32m                              *"
echo "   ********************************************************************"
echo " "
echo "\33[1;36m   1)\33[0m Actualizar Dispositivo (update y upgrade)"
echo "\33[1;36m   2)\33[0m Instalar svxlink 15.11"
echo "\33[1;36m   3)\33[0m Editar el fichero ModuleEchoLink.conf y svxlink"
echo "\33[1;36m   4)\33[0m Poner en el autoarranque el svxlink"
echo "\33[1;36m   5)\33[0m Instalar ficheros de audio"
echo " "
echo "\33[1;36m   0)\33[1;34m  <Para Salir>"
echo ""

echo "\33[1;36m   Escoge una opción.. 1,2,3,4,0 \33[1;33m " 
read escoger_menu
echo ""

case $escoger_menu in
1) echo ""

while true
do
clear

	        read -p 'Quieres actualizar Si/No: ' actualizar
		    case $actualizar in
			[sS]* ) echo ""
			echo "Estado: Actualizando >>>>>"
			sudo apt-get update
			sudo apt-get upgrade
			echo ""
			echo "Ok, se ha actualizado todo correctamente"
			echo ""
			break;;
			[nN]* ) echo ""
			break;;
			#* )	echo "Por favor elige Y o N";;
esac
done;;
2) 	echo ""

while true
do
clear
			echo ""
			echo ""
			echo ""
		    read -p 'Descargar e instalar svxlink Si/No ' installvar
			case $installvar in
			[sS]* ) echo ""
			echo "Descargando svxlink 15.11"
                              wget https://github.com/sm0svx/svxlink/archive/15.11.tar.gz
			tar xzvf 15.11.tar.gz
			sudo apt-get install g++ make libsigc++-2.0-dev libgsm1-dev libpopt-dev tcl8.5-dev libgcrypt11-dev libspeex-dev libasound2-dev alsa-utils vorbis-tools  cmake libqt4-dev
			cd svxlink-15.11
			cd src	
			mkdir build
			cd build
			cmake ..
			make
			sleep 3
			sudo adduser svxlink
			sudo make install
			sudo ldconfig -v
			break;;
			[nN]* ) echo ""
			echo ""
			echo ""
			echo "volver"
			echo ""
			echo ""
			echo ""
			break;;			
esac
done;;

3) 	echo ""

while true
do
clear
                              seguir=S
			case $seguir in
			[sS]* ) echo ""
clear
                              lxterminal --geometry=100x40 -e sudo sh editar_svxlink.sh
			break;;
			[nN]* ) echo ""
			echo ""
			echo ""
			echo "volver"
			echo ""
			echo ""
			echo ""
			break;;			
esac

done;;
4) 	echo ""

while true
do
clear
                              seguir=S
			case $seguir in
			[sS]* ) echo ""
                              clear
			sudo chmod 755 inicio_svxlink.desktop
			sudo mv inicio_svxlink.desktop ~/.config/autostart	
			break;;
			[nN]* ) echo ""
			echo ""
			echo ""
			echo "volver"
			echo ""
			echo ""
			echo ""
			break;;			
esac

done;;
5) 	echo ""

while true
do
clear
                              seguir=S
			case $seguir in
			[sS]* ) echo ""
clear
                              wget https://github.com/sm0svx/svxlink-sounds-en_US-heather/releases/download/14.08/svxlink-sounds-en_US-heather-16k-13.12.tar.bz2
			tar jvfx svxlink-sounds-en_US-heather-16k-13.12.tar.bz2
			sudo mkdir /usr/local/share/svxlink/sounds/en_US
			cd en_US-heather-16k
			sudo cp -r * /usr/local/share/svxlink/sounds/en_US
			echo "Ficheros de audio instalados correctamente"
			sleep 3
			break;;
			[nN]* ) echo ""
			echo ""
			echo ""
			echo "volver"
			echo ""
			echo ""
			echo ""
			break;;			
esac

done;;	
0) echo ""
clear
echo "   **************************************************"
echo "   *                                                *"
echo "   *     CERRANDO SCRIPT SVXLINK 15.11 BY EA3EIZ    *"
echo "   *                                                *"
echo "   **************************************************"
sleep 3
clear
exit;;	
esac
done


